---
#              _             __      _       __     ___            _        
#  _ __   __ _(_)_ __ __  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _` | | '_ \\ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | | | (_| | | | | |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_| |_|\__, |_|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#        |___/              \_\_|        |___/_/                            
# php-fastcgi
- block:
    - name: php-fastcgi | Amazon | PHP {{ nginx.php.version }} repository should be enabled
      when: ansible_distribution == "Amazon"
      shell: amazon-linux-extras list | grep php{{ nginx.php.version }} | grep enabled || amazon-linux-extras enable php{{ nginx.php.version }}
      changed_when: false

    - name: php-fastcgi | RedHat | PHP packages should be installed
      yum:
        state: "present"
        name:
          - "php"
          - "php-common"
          - "php-devel"
          - "php-pear"
          - "php-pdo"
          - "php-cli"
          - "php-gd"
          - "php-mbstring"
          - "php-pgsql"
          - "php-mysqlnd"
          - "php-xml"
          - "php-fpm"

    - name: php-fastcgi | Deploy /etc/php.ini
      notify: Restart php-fpm
      template:
        src:  "etc/php.ini.j2"
        dest: "/etc/php.ini"
        mode: "0644"

    - name: php-fastcgi | Deploy each config file in /etc/php.d
      notify: Restart php-fpm
      template:
        src:  "{{ item }}"
        dest: "/etc/php.d/{{ item | basename | replace('.j2', '') }}"
        mode: "0644"
      with_fileglob: "templates/etc/php.d/*.ini.j2"

    - name: php-fastcgi | Deploy /etc/php-fpm.d/www.conf
      notify: Restart php-fpm
      template:
        src:  "etc/php-fpm.d/www.conf.j2"
        dest: "/etc/php-fpm.d/www.conf"
        mode: "0644"
  when: ansible_os_family == "RedHat"

- name: php-fastcgi | php-fpm should be started
  when: nginx.started == true
  service:
    name:    "php-fpm"
    enabled: "yes"

- name: php-fastcgi | php-fpm should be enabled
  when: nginx.enabled == true
  service:
    name:  "php-fpm"
    state: "started"

