---
#              _             __      _       __     ___                     _ _               
#  _ __   __ _(_)_ __ __  __/ /_ __ | | ____ \ \   / / |__   __ _ _ __   __| | | ___ _ __ ___ 
# | '_ \ / _` | | '_ \\ \/ / || '_ \| |/ / _` | | / /| '_ \ / _` | '_ \ / _` | |/ _ \ '__/ __|
# | | | | (_| | | | | |>  <| || |_) |   < (_| | |/ / | | | | (_| | | | | (_| | |  __/ |  \__ \
# |_| |_|\__, |_|_| |_/_/\_\ || .__/|_|\_\__, | /_/  |_| |_|\__,_|_| |_|\__,_|_|\___|_|  |___/
#        |___/              \_\_|        |___/_/                                              
# handlers file for ar-nginx-pkg
- name: Restart NGINX
  service:
    name:  "nginx"
    state: "restarted"

- name: Restart php-fpm
  when: nginx.php.fastcgi == true
  service:
    name:  "php-fpm"
    state: "restarted"

